# Generated by Django 5.2.6 on 2025-09-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200, verbose_name="From")),
                ("phone_number", models.CharField(max_length=15)),
                ("registration_time", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(blank=True, default=None, null=True)),
                ("extra_info_1", models.TextField(blank=True, null=True)),
                ("extra_info_2", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("score"), descending=True, nulls_last=True),
                    "registration_time",
                ],
            },
        ),
    ]
